import { nativeAndroid } from '../native/platform';
import * as web from './web';
import * as native from './native';
export { db, FieldbookDB } from './web';
const store = nativeAndroid ? native : web;
export const getQuery = store.getQuery;
export const saveQuery = store.saveQuery;
export const getSightings = store.getSightings;
export const saveSighting = store.saveSighting;
export const retractSighting = store.retractSighting;
export const getRetractions = store.getRetractions;
export const sightingIds = store.sightingIds;
export const getSighting = store.getSighting;
export const restoreSighting = store.restoreSighting;
export const getSettings = store.getSettings;
export const saveSettings = store.saveSettings;
export const visitCell = store.visitCell;
export const readTile = store.readTile;
export const saveTile = store.saveTile;
export const exportNotebook = store.exportNotebook;
export const storageStats = store.storageStats;
export const getVisitedCells = store.getVisitedCells;
export const getStoredSpecies = store.getStoredSpecies;
export const saveSpecies = store.saveSpecies;
export const getSeason = store.getSeason;
export const saveSeason = store.saveSeason;
export const getEmbedding = store.getEmbedding;
export const saveEmbedding = store.saveEmbedding;
export const getRange = store.getRange;
export const saveRange = store.saveRange;
export const getEmbeddings = store.getEmbeddings;
export const saveEmbeddings = store.saveEmbeddings;
export const getSeasonsForCell = store.getSeasonsForCell;
export const watchCollection = store.watchCollection;
export const searchStoredSpecies = store.searchStoredSpecies;
export const restoreVisit = store.restoreVisit;
