// Generated by merge_plant_recovery_content.py.
import part0 from './part-000.json';
import part1 from './part-001.json';
import part2 from './part-002.json';
import part3 from './part-003.json';
import part4 from './part-004.json';
import part5 from './part-005.json';
import part6 from './part-006.json';
import part7 from './part-007.json';
export default { stories: [...part0, ...part1, ...part2, ...part3, ...part4, ...part5, ...part6, ...part7] };
