import type { Habitat } from '../src/types';
export const habitatLabels: Record<Habitat, string> = {
  ocean: 'Sea',
  water: 'Water',
  lake: 'Lake',
  river: 'River',
  wetland: 'Wetland',
  wood: 'Woodland',
  grassland: 'Grassland',
  scrub: 'Scrub',
  farmland: 'Farmland',
  'built-up': 'Built-up ground',
  coast: 'Coastal ground',
  'open-ground': 'Open ground',
  unknown: 'Habitat unavailable',
};
export const habitatKinds: Record<string, Habitat> = {
  ocean: 'ocean',
  sea: 'ocean',
  lake: 'lake',
  reservoir: 'lake',
  water: 'water',
  river: 'river',
  stream: 'river',
  canal: 'river',
  wetland: 'wetland',
  marsh: 'wetland',
  swamp: 'wetland',
  forest: 'wood',
  wood: 'wood',
  grass: 'grassland',
  grassland: 'grassland',
  meadow: 'grassland',
  park: 'grassland',
  scrub: 'scrub',
  heath: 'scrub',
  farmland: 'farmland',
  farmyard: 'farmland',
  orchard: 'farmland',
  vineyard: 'farmland',
  residential: 'built-up',
  commercial: 'built-up',
  industrial: 'built-up',
  building: 'built-up',
  urban_area: 'built-up',
  beach: 'coast',
  sand: 'coast',
  bare_rock: 'open-ground',
  earth: 'open-ground',
};
export const habitatPriority: Record<Habitat, number> = {
  unknown: 0,
  ocean: 1,
  'open-ground': 2,
  grassland: 3,
  scrub: 4,
  farmland: 5,
  wood: 6,
  coast: 7,
  'built-up': 8,
  wetland: 9,
  water: 10,
  lake: 10,
  river: 11,
};
