#!/usr/bin/env python3
"""Import an explicit slice of validated CLI drafts into species-card content."""
import argparse
import hashlib

from audit_plant_content import ROOT, SOURCE, read, write
from run_plant_content_cli import validate


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--run', required=True)
    parser.add_argument('--count', type=int, required=True)
    parser.add_argument('--skip-failed', action='store_true', help='Explicitly exclude saved failed results from the selected slice')
    args = parser.parse_args()
    base = ROOT/args.run
    manifest = read(base/'manifest.json')
    assert 0 < args.count <= manifest['count']
    selected = manifest['taxonIds'][:args.count]
    stories = []
    skipped = []
    for tid in selected:
        result = read(base/f'{tid}-result.json')
        frozen = read(base/f'{tid}-source.json')
        packet = frozen['input']
        assert result['taxonId'] == packet['taxonId'] == tid
        if not result['validated']:
            assert args.skip_failed, f'Failed result {tid}; use --skip-failed to exclude it explicitly'
            skipped.append(tid)
            continue
        validate(result['output'], packet)
        record = read(SOURCE/'taxa'/f'{tid}.json')
        botanical = {r['path']: r for r in record['botanicalSources']}
        sources = []
        for source, provenance in zip(packet['sources'], frozen['sourceProvenance']):
            original = read(SOURCE/provenance['path'])
            if 'wikitext' in original:
                assert original['contentSha256'] == provenance['sha256']
                sources.append({'id': source['id'], 'title': source['title'], 'url': original['url'],
                    'revisionUrl': provenance['url'], 'attribution': original['attribution'],
                    'license': original['rights']['text'], 'licenseUrl': original['rights']['url']})
            else:
                ref = botanical[provenance['path']]
                assert ref['recordSha256'] == provenance['sha256']
                sources.append({'id': source['id'], 'title': source['title'], 'url': provenance['url'],
                    'attribution': ref['citation']['text'], 'licenseUrl': ref['license']})
        output = result['output']
        stories.append({'taxonId': tid, 'tags': [], 'summary': output['summary'],
                        'humanEdibility': output['humanEdibility'], 'edibilityNote': output['edibilityNote'],
                        'reviewStatus': 'draft', 'sources': sources})
    seed = read(ROOT/'config/seed.json')
    path = ROOT/'stories'/seed['country']/f"{seed['group']}.cli.json"
    write(path, {'schemaVersion': 1, 'sourceRun': args.run,
                 'manifestSha256': hashlib.sha256((base/'manifest.json').read_bytes()).hexdigest(),
                 'selection': f'Validated records from the first {args.count} plants in frozen manifest order; {len(skipped)} failed records excluded; user-authorised card import.',
                 'count': len(stories), 'stories': stories})
    # Keep each bundled asset within the service worker's offline cache limit.
    chunks = path.with_suffix('')
    chunks.mkdir(parents=True, exist_ok=True)
    imports = []
    names = []
    for index, start in enumerate(range(0, len(stories), 1000)):
        filename = f'part-{index:03d}.json'
        write(chunks/filename, stories[start:start+1000])
        imports.append(f"import part{index} from './{filename}';")
        names.append(f'...part{index}')
    (chunks/'index.ts').write_text('// Generated by import_plant_cli_content.py.\n' +
                                 '\n'.join(imports) + '\nexport default { stories: [' +
                                 ', '.join(names) + '] };\n')
    write(base/'card-import.json', {'count': len(stories), 'taxonIds': [s['taxonId'] for s in stories],
          'selectedCount': len(selected), 'skippedFailedTaxonIds': skipped,
          'destination': str(path.relative_to(ROOT)), 'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
          'nullSummaryCount': sum(s['summary'] is None for s in stories),
          'reviewStatus': 'draft', 'botanicalAccuracyReviewed': False})
    print(f'Imported {len(stories)} validated records to {path}; excluded {len(skipped)} failed records')


if __name__ == '__main__':
    main()
